### ISSUE TITLE
[1.12] Blocks from Futurepack mod are mixed up by swapping wand

### ISSUE THREAD

**Issue by donqixot** [romelo333/notenoughwands#60]
First, thank you very much for this mod! It is amazing!

I am trying to use swapping wand for blocks from mod Futurepack (https://minecraft.curseforge.com/projects/futurepack). Ore names are fp:erze and metadata can be 0-7. Wand sort of works by replacing ore with my blocks of choice, but it always gives me back block with metadata 0 (fp:erze:0, which is Tin). Copper has metadata 2, when swapping takes place, I am still getting Tin, not Copper. Strangely enough, for other blocks from this mod (example fp:color_iron) this does not happen! Any chance you can look if this is Futurepack mod issue or yours?

I am using your latest version 1.12-1.5.7 and latest from Futurepack - 1.12-26.1.1. Forge 14.21.1.2387 (and also 14.21.1.2389).

**Comment by McJty** [comment]
I'm using block.getItem() for this. If that's not working then I think that's a bug on their side

**Comment by DwellerBenthos** [comment]
I think I'm having a similar issue, using the swapping wand on various mod ores. especially in the nether. Playing on the GangZcraft modpack.

I reported a crash for Silent's Gems here https://github.com/SilentChaos512/SilentGems/issues/183 where nether ores for that mod are being changed from the ore to an item that has the no texture error and do not respond as the ores until you place them again, where they are converted back to the proper texture and can be mined. The crash occurred when my inventory was full and the swapped ores then popped out into the world as entities and crashed. The world would not load until the entities were deleted in MC Edit.

I also had a crash with Substratum's nether ores using the swapping wand and that happened as soon as I opened my inventory after swapping the ores over. They also had the no texture error, and the crash happened as soon as inventory was opened, until the offending items were deleted from the inventory using MC Edit. Here is the crash report for that error 

https://pastebin.com/nRRbgnmv

Though it's an error with Substratum, I'm posting here because it seems the swapping wand was the cause.

This is using version notenoughwands-1.1x-1.5.5, if this is an issue with how the other mods are naming their items as mentioned above, then please post a note I can point the other mod authors to explaining what the issue may be?

**Comment by mcenderdragon** [comment]
I use getDrops, since their it also changes coal ore to coal items (same wit quartz)

**Comment by McJty** [comment]
I use getPickBlock() now which should fix this issue in the next release
